#!/usr/bin/env python
import urllib2, json
import yaml
import platform
from sys import exit
from random import randrange
from os import system, mkdir, environ
from os.path import basename, realpath, dirname, isdir

class ImgurNSFW:
    def __init__(self):
        self.script_path = dirname(realpath(__file__))
        self.__key       = None
        self.__gallery   = None
        self.__type      = None

    def getScriptPath(self):
        return self.script_path

    def setKey(self, key):
        self.__key = key

    def getKey(self):
        return self.__key

    def setGallery(self, gallery):
        self.__gallery = gallery

    def getGallery(self):
        return self.__gallery

    def setType(self, type):
        self.__type = type

    def getType(self):
        return self.__type

    def getWallpaper(self):
        req = urllib2.Request('https://api.imgur.com/3/gallery/'+ self.getGallery() + '/' + self.getType())
        req.add_header('Authorization', 'Client-ID ' + self.getKey())

        try:
            result = urllib2.urlopen(req)
            data   = json.loads(result.read())
        except urllib2.HTTPError:
            data = None

        if data == None:
            return False

        return data['data'][randrange(0, len(data['data']))]['link']

    def saveWallpaper(self, image):
        filename = basename(image)

        with open(self.script_path + '/wallpapers/' + filename, 'w') as f:
            req    = urllib2.Request(image)
            result = urllib2.urlopen(req).read()

            f.write(result)

        return self.script_path + '/wallpapers/' + filename

def getDE():
    # http://ubuntuforums.org/showthread.php?t=1139057
    desktop_environment = 'generic'
    if environ.get('KDE_FULL_SESSION') == 'true':
        desktop_environment = 'kde'
    elif environ.get('GNOME_DESKTOP_SESSION_ID'):
        desktop_environment = 'gnome'
    else:
        try:
            info = getoutput('xprop -root _DT_SAVE_MODE')
            if ' = "xfce4"' in info:
                desktop_environment = 'xfce'
        except (OSError, RuntimeError):
            pass

    return desktop_environment

nsfw   = ImgurNSFW()
config = yaml.load(open(nsfw.getScriptPath() + '/config.yml', 'r'))
nsfw.setKey(config['key'])
nsfw.setGallery(config['gallery'])
nsfw.setType(config['type'])

if not isdir(nsfw.getScriptPath() + '/wallpapers'):
    mkdir(nsfw.getScriptPath() + '/wallpapers')

wallpaper = nsfw.getWallpaper()
if wallpaper == False:
    exit()

wallpaper_path = nsfw.saveWallpaper(wallpaper)

platform = platform.system().lower()
de       = getDE()

if platform == 'linux':
    if de == 'gnome':
        system('DISPLAY=:0 GSETTINGS_BACKEND=dconf gsettings set org.gnome.desktop.background picture-uri file://' + wallpaper_path)
        system('DISPLAY=:0 GSETTINGS_BACKEND=dconf gsettings set org.gnome.desktop.background picture-options zoom')
elif platform == 'darwin':
    script = """/usr/bin/osascript<<END
tell application "Finder"
set desktop picture to POSIX file "%s"
end tell
END"""
    system(script % wallpaper_path)